---
layout: post
title: ""

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(screenshot.force = FALSE)
```

Leaflet map test...

```{r, echo=F, warning=F, message=F}

library(rebird)
library(leaflet)
library(leaflet.extras)
library(dplyr)

kestrel_sites_US<-ebirdregion(region = 'US', species = 'Falco sparverius', hotspot=FALSE)
kestrel_sites_MX<-ebirdregion(region = 'MX', species = 'Falco sparverius', hotspot=FALSE)
kestrel_sites_BS<-ebirdregion(region = 'BS', species = 'Falco sparverius', hotspot=FALSE)
kestrel_sites_PA<-ebirdregion(region = 'PA', species = 'Falco sparverius', hotspot=FALSE)
kestrel_sites_CU<-ebirdregion(region = 'CU', species = 'Falco sparverius', hotspot=FALSE)

kestrel_sites_US<-kestrel_sites_US %>% 
  filter(lat < 50) %>%
sample_n(50)

kestrel_sites_MX<-kestrel_sites_MX %>% 
  sample_n(10)

kestrel_sites_BS<-kestrel_sites_BS %>% 
  sample_n(3)

kestrel_sites_PA<-kestrel_sites_PA %>% 
  sample_n(5)

kestrel_sites_CU<-kestrel_sites_CU %>% 
  sample_n(2)

kestrel_sites_US$Region<-"US"
kestrel_sites_MX$Region<-"Mexico"
kestrel_sites_BS$Region<-"Bahamas"
kestrel_sites_PA$Region<-"Panama"
kestrel_sites_CU$Region<-"Cuba"

kestrel_sites<-rbind(kestrel_sites_US,
                     kestrel_sites_MX,
                     kestrel_sites_BS,
                     kestrel_sites_PA,
                     kestrel_sites_CU)

#head(kestrel_sites)

pal <- colorFactor(ggthemes::gdocs_pal()(5), kestrel_sites$Region)

AMKE_popup <- paste0("<strong>Name: </strong>", 
      kestrel_sites$sciName, 
      "<br><strong>Observation date: </strong>", 
      kestrel_sites$obsDt)

m <- leaflet(kestrel_sites) %>% 
  addCircleMarkers(~lng, ~lat, popup=AMKE_popup,
                   weight = 20, color=NA, group="AMKE locations",
                   fillOpacity = 0.5, radius = 8,
                   fillColor = pal(kestrel_sites$Region)) %>%
  addLegend(position = 'bottomleft', pal = pal, values = kestrel_sites$Region) %>%
  # Add tiles
  addProviderTiles("Stamen.Terrain", group = "Topographical") %>%
  addProviderTiles("OpenStreetMap.Mapnik", group = "Road map") %>%
  #setView(lng = -98.5795, lat = 39.8282,  zoom = 3.5) %>% 
  addLayersControl(position = 'bottomright',
                   baseGroups = c("Topographical", "Road map"),
                   overlayGroups = c("AMKE locations"),
                   options = layersControlOptions(collapsed = FALSE))
m

```